//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeControl.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchiveProduct
    {
        public int ArchiveId { get; set; }
        public int ProductsId { get; set; }
        public string ProductsName { get; set; }
        public int UnitsInStock { get; set; }
        public decimal UnitPrice { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
