//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeControl.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int InventoryId { get; set; }
        public int ProductsId { get; set; }
        public string ProductsName { get; set; }
        public int StoreLocation { get; set; }
        public System.DateTime SoldDate { get; set; }
        public int UnitPrice { get; set; }
        public Nullable<int> Discount { get; set; }
        public int FinalPrice { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual StoreLocation StoreLocation1 { get; set; }
    }
}
